# Generated by Django 6.0.3 on 2026-03-29 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browsed_at', models.DateTimeField(auto_now_add=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=20)),
                ('products_shown', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-browsed_at',),
            },
        ),
    ]
